// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxkzcsduxaeziwfwbcyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4a3pjc2R1eGFleml3ZndiY3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTA5OTQsImV4cCI6MjA2Njg2Njk5NH0.OZ0Jcil6tgHFonCwmt-4oZcCf3gKCX37S9y8qKHvz-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});